SMA_long = 158
SMA_short = 57

BULL_rsi = 20
BULL_high = 85
BULL_low = 54
BULL_mod_high = 8
BULL_mod_low = 0

BEAR_rsi = 25
BEAR_high = 61
BEAR_low = 16
BEAR_mod_high = 6
BEAR_mod_low  = 0

ADX_adx = 6
ADX_high = 58
ADX_low = 30

STOP_LOSS = 10